export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'

export const LOAD_STATE = 'LOAD_STATE'
export const SET_STATE = 'SET_STATE'

export const ADD_RECORD = 'ADD_RECORD'
export const CHANGE_RECORD = 'CHANGE_RECORD'
export const DELETE_RECORD = 'DELETE_RECORD'
