export const ADD_DEPARTMENT = 'ADD_DEPARTMENT'
export const CHANGE_DEPARTMENT = 'CHANGE_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'

export const ADD_EMPLOYEE = 'ADD_EMPLOYEE'
export const CHANGE_EMPLOYEE = 'CHANGE_EMPLOYEE'
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE'
